### ISSUE TITLE
add keymap for easier navigate UP/DOWN in soft mode

### ISSUE THREAD

**Issue by destnguyxn** [andrewferrier/wrapping.nvim#39]
a simple key map that help us easily navigate like this
```
vim.keymap.set("n", "j", "<Down>")
vim.keymap.set("n", "k", "<Up>")
```
but mine does not work in ftplugin/markdown.lua

**Comment by andrewferrier** [comment]
@destnguyxn `wrapping.nvim` does remap `<Up>` and `<Down>` already; it makes them consistent with the behaviour of `gk` and `gj` in NeoVim which move by display line rather than 'real' line; note that this doesn't affect the behaviour of 'j' and 'k', which is intentional. Your mapping isn't recursive, though, which may be why it's not having any effect. Look up `remap` for `vim.keymap.set()` :)

**Comment by andrewferrier** [comment]
Closing due to lack of response.
