### ISSUE TITLE
Add indicators for lines that have been wrapped

### ISSUE THREAD

**Issue by avih7531** [andrewferrier/wrapping.nvim#43]
```
I think a nice feature to add would be indicators if a line is wrapped.

Non-Wrapped
1       public static void main(String[] args) {
2              System.out.println("Wow. Wrapping text is so, so cool")
3       }

Wrapped
1       public static void main(String[] args) {
2              System.out.println("Wow. Wrapping text
        is so, so cool")
3       }

Wrapped Indicated 1st Way
1       public static void main(String[] args) {
2              System.out.println("Wow. Wrapping text
        󱞩 is so, so cool")
3       }

Wrapped Indicated 2nd Way
1       public static void main(String[] args) {
2              System.out.println("Wow. Wrapping text
               󱞩 is so, so cool")
3       }

I used this type of wrapping in Jupyter Notebook a while ago in school, and I found it to be the best way to recognize a wrapped line (Jupyter Notebook uses the 2nd way I proposed). If for some reason you can't see it, that icon is NerdFont md-arrow_right_bottom.

I think there could be options for indicator icon, color, and whether or not to put it in the first character spot on the new line where the wrapped line starts (like in my 1st example), or under the first character under the line that is being wrapped (like in my 2nd example) .

I'd totally make this, but I'm useless at Lua :)

**Comment by avih7531** [comment]
Sorry for the code block. It was the only way I could get Github to recognize my weird formatting.

**Comment by andrewferrier** [comment]
This is an interesting idea. I think to implement this would probably need NeoVim extmarks. It's not easy though, as they'll move around as the text is edited.

I'll leave this open here in case anyone wants to take this on, but right I'm not sure it's something I can spend any time on, it's probably non-trivial. I think this would ultimately be better as a built-in NeoVim feature.

**Comment by avih7531** [comment]
Thanks for your interest, Andrew! 

I definitely agree that it won't be trivial to implement, but I forked this repo and I'll give it my best shot with a buddy over the next week or so but by all means if someone wants to save me :wink:

**Comment by avih7531** [comment]
Hi! Now that Nvim 0.10 is out and has the status column feature, could this feature be implemented in the next update?

**Comment by andrewferrier** [comment]
There's no easy way to do this in the general sense; the `vim.opt.statuscolumn` option is typically used for a number of things, such as customizing line numbers, diagnostic marks, etc. Everyone uses it differently (or will), so an implementation in `wrapping.nvim` by itself wouldn't really make sense and would probably out of the scope of this plugin. It would probably make more sense to request this as a feature in a status column plugin like `https://github.com/luukvbaal/statuscol.nvim`, since there is nothing specific to `wrapping.nvim` about the lines that are wrapped; it's NeoVim itself that does the wrapping, not this plugin.

For now, I'm going to close this issue. Thanks for your thoughts and input.
